name: Update MIME Data

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs on a schedule (e.g., every Sunday at 02:00 UTC)
  schedule:
    - cron: '0 2 * * 0'

jobs:
  update-mime-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Or whatever version you prefer

      # 3. Run the generator program
      # This will fetch the latest XML and create/update the data.go file.
      - name: Run MIME data generator
        run: go run ./cmd/generator

      # 4. Commit and push the changes if data.go was modified
      # This action checks for any changes in the git working tree.
      # If there are changes, it commits them and pushes to the repository.
      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): Update MIME descriptions from freedesktop.org"
          branch: main # Or your default branch
          file_pattern: data.go # Only commit changes to the data.go file
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions@github.com"
          commit_author: "GitHub Actions Bot <github-actions@github.com>"